### PR TITLE
Modification of  CACertificateFilter system filter to allow only non CA certificate types

### PR DESCRIPTION
**Pull request by vineela-pachchipulusu**
Modifying CACertificateFilter system filter to allow only non CA certificate types
Removing https_enabled from the controllers/host/host_controller_fixtures.go

Test plan:

Generation of deployment config using deployctl

### CODE REVIEW

**Review by yjian118 — CHANGES_REQUESTED** [review]
PlatformCACertificate should still be ignored, please don't change the logic to filter out legacy certs

**Review by mcloebens — COMMENTED** [review]
I think you should modify the description/title of the review/commit, since this isn't cleaning up examples. It's cleaning references in code.

**Comment by vineela-pachchipulusu** [comment]
> PlatformCACertificate should still be ignored, please don't change the logic to filter out legacy certs

Modified accordingly

**Comment by mcloebens** [comment]
lgtm.

**Review by mcloebens — COMMENTED** [review]
lgtm.

**Review by mcloebens — APPROVED** [review]
lgtm.

**Comment by vineela-pachchipulusu** [comment]
> I think you should modify the description/title of the review/commit, since this isn't cleaning up examples. It's cleaning references in code.

Have modified the description and title accordingly

**Review by yjian118 — APPROVED** [review]

**Pull request merged**
