### PR TITLE
Add support for ethernet type interface on ethernet interface

### PR DESCRIPTION
**Pull request by gaolitao**
This is the 1st part of the DM modification for sharing single nic.
2nd part for rate limiting is being prepared now.
Need to send pull request to involve core developer as early as possible.
--------------------------------------------------------------------------

In order to support configuring CaaS and Data networks to single VF
capable NIC, we add support for creating ethernet type interface on
top of ethernet interface which is actually class of pci-sriov.
https://storyboard.openstack.org/#!/story/2008470

This way, on top of a same pci-sriov ethernet interface, we can:
- create an untagged ethernet interface for pxeboot platform network.
- create vlan tagged interfaces for oam, internal-mgmt and cluster-host
- create vf type sub-interfaces for data networks

Signed-off-by: Litao Gao <litao.gao@windriver.com>

### CODE REVIEW

**Review by albailey — COMMENTED** [review]
syntax looks fine.

**Review by mwang3-wrs — APPROVED** [review]

**Comment by donpenney** [comment]
Is there a change needed in the "deploy" utility, either to update the filters or to have new data in the generated model? I would recommend running the tool to verify it creates the expected config model, if you haven't already done so. You'll find it as part of your build output in the bin dir, and can copy it to your controller to run something like:
deploy --system-name mysystem --minimal-config

See "deploy build -h" for options

**Comment by steven-webster** [comment]
Looks ok to me

**Comment by gaolitao** [comment]
> 
> 
> Is there a change needed in the "deploy" utility, either to update the filters or to have new data in the generated model? I would recommend running the tool to verify it creates the expected config model, if you haven't already done so. You'll find it as part of your build output in the bin dir, and can copy it to your controller to run something like:
> deploy --system-name mysystem --minimal-config
> 
> See "deploy build -h" for options

Yes, the change for "deploy" utility is in pkg/apis/starlingx/v1/constructors.go

My testing process is: 
1. use deploy tool to generate a deployment-config.yaml 
2. install newly built DM helm application 
3. kubectl apply the deployment-config.yaml 
4. make sure the interfaces are reconciled and synced.

**Review by donpenney — APPROVED** [review]

**Comment by donpenney** [comment]
> 
> 
> > Is there a change needed in the "deploy" utility, either to update the filters or to have new data in the generated model? I would recommend running the tool to verify it creates the expected config model, if you haven't already done so. You'll find it as part of your build output in the bin dir, and can copy it to your controller to run something like:
> > deploy --system-name mysystem --minimal-config
> > See "deploy build -h" for options
> 
> Yes, the change for "deploy" utility is in pkg/apis/starlingx/v1/constructors.go
> 
> My testing process is:
> 
>     1. use deploy tool to generate a deployment-config.yaml
> 
>     2. install newly built DM helm application
> 
>     3. kubectl apply the deployment-config.yaml
> 
>     4. make sure the interfaces are reconciled and synced.

Perfect... thank you!

**Pull request merged**
