### PR TITLE
rename deploy to deployctl

### PR DESCRIPTION
**Pull request by sharbhar**
renaming deploy to deployctl

Test Plan:
Pass: Run the make command
Pass: Docker-build
Pass: Make tools

deployctl is generated in bin/ path

### CODE REVIEW

**Comment by hugonicodemos** [comment]
Hi @sharbhar. nit: Here is a public repo, we don't use the JIRA number.

**Comment by sharbhar** [comment]
Hi Hugo,

Removed.

Thanks
Sharang
________________________________

**Review by hugonicodemos — CHANGES_REQUESTED** [review]
Rename the sections: `Building The deploy Tool` and `Using The deploy Tool` to deployctl as well. (in the description of these sections we have some renaming also)

**Review by sselvara1 — APPROVED** [review]
LGTM

**Review by hugonicodemos — APPROVED** [review]

**Pull request merged**
