### PR TITLE
Reverting implementation of subcloud add without upload

### PR DESCRIPTION
**Pull request by sharbhar**
Need to set default value for user_uploaded_artifacts
if we can playbook standalone, it would fail with not-defined.

### CODE REVIEW

**Comment by yjian118** [comment]
Why do you want to revert the previous commit? Need to add the description

**Review by yjian118 — APPROVED** [review]
As it is a simple revert, I'll merge it

**Comment by yjian118** [comment]
Need to resolve the merge conflicts

**Comment by sharbhar** [comment]
> Need to resolve the merge conflicts

No merge conflicts

**Pull request merged**
